Repository Tech-Community-Peru/tech-events-front, pull requests merged in 2024-11, with the labels that each got.

#1 Feature/dashboardtcp
  public/escenario2.jpg
  public/logo-sin-fondo.ico
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.config.ts
  src/app/app.routes.ts
  src/app/core/services/event.service.spec.ts
  src/app/core/services/event.service.ts
  src/app/pages/event-detail/event-detail.component.css
  src/app/pages/event-detail/event-detail.component.html
  src/app/pages/event-detail/event-detail.component.ts
  src/app/pages/event-list/event-list.component.css
  src/app/pages/event-list/event-list.component.html
  src/app/pages/event-list/event-list.component.ts
  src/app/pages/participante/dashboard/dashboard.component.css
  src/app/pages/participante/dashboard/dashboard.component.html
  src/app/pages/participante/dashboard/dashboard.component.ts
  src/app/shared/components/footer/footer.component.css
  src/app/shared/components/footer/footer.component.html
  src/app/shared/components/navbar/navbar.component.css
  src/app/shared/components/navbar/navbar.component.html
  src/app/shared/components/navbar/navbar.component.ts
  src/environments/environment.development.ts
  src/index.html
  src/main.ts
Labels: Fronted

#21 Feature/vista ponente
  package-lock.json
  package.json
  src/app/app.routes.ts
  src/app/core/service/auth.service.ts
  src/app/core/service/storage.service.ts
  src/app/core/services/event.service.ts
  src/app/pages/auth/auth.routes.ts
  src/app/pages/auth/login/login.component.html
  src/app/pages/auth/register-ponente/register-ponente.component.css
  src/app/pages/auth/register-ponente/register-ponente.component.html
  src/app/pages/auth/register-ponente/register-ponente.component.ts
  src/app/pages/event-list/event-list.component.ts
  src/app/pages/inscription/inscription.component.css
  src/app/pages/inscription/inscription.component.html
  src/app/pages/inscription/inscription.component.spec.ts
  src/app/pages/inscription/inscription.component.ts
  src/app/pages/participante/dashboard/dashboard.component.html
  src/app/shared/components/navbar/navbar.component.css
  src/app/shared/models/auth-response.model.ts
  src/app/shared/models/categoryEvent.model.ts
  src/app/shared/models/evento-response.model.ts
  src/app/shared/models/register-requestPonente.model.ts
  src/app/shared/models/register-responsePonente.model.ts
  src/app/shared/models/typeEvent.model.ts
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: Fronted

#23 Feature/inscripcion
  src/app/core/service/auth.service.ts
  src/app/core/service/storage.service.ts
  src/app/core/services/event.service.ts
  src/app/pages/auth/login/login.component.ts
  src/app/pages/inscription/inscription.component.html
  src/app/pages/inscription/inscription.component.ts
  src/app/shared/models/auth-response.model.ts
  src/app/shared/models/register-response.model.ts
Labels: Fronted

#24 Feature/user profile
  src/app/app.routes.ts
  src/app/core/service/auth.service.ts
  src/app/core/service/perfil.service.ts
  src/app/core/service/storage.service.ts
  src/app/pages/perfil/perfil.component.css
  src/app/pages/perfil/perfil.component.html
  src/app/pages/perfil/perfil.component.spec.ts
  src/app/pages/perfil/perfil.component.ts
  src/app/shared/components/navbar/navbar.component.html
  src/app/shared/components/update-profile-ponente/update-profile-ponente.component.html
  src/app/shared/components/update-profile-ponente/update-profile-ponente.component.ts
  src/app/shared/components/update-profile/update-profile.component.css
  src/app/shared/components/update-profile/update-profile.component.html
  src/app/shared/components/update-profile/update-profile.component.ts
  src/app/shared/components/user-profile/user-profile.component.css
  src/app/shared/components/user-profile/user-profile.component.html
  src/app/shared/components/user-profile/user-profile.component.ts
  src/app/shared/models/actualizarperfil-request.model.ts
  src/app/shared/models/actualizarperfil-response.model.ts
  src/app/shared/models/register-response.model.ts
Labels: Fronted

#25 Feature/filtrar Eventos
  src/app/core/services/event.service.ts
  src/app/pages/event-list/event-list.component.css
  src/app/pages/event-list/event-list.component.html
  src/app/pages/event-list/event-list.component.ts
  src/app/pages/inscription/inscription.component.html
  src/app/shared/components/footer/footer.component.html
  src/app/shared/components/update-profile/update-profile.component.css
  src/app/shared/components/update-profile/update-profile.component.html
  src/app/shared/components/user-profile/user-profile.component.html
Labels: Fronted

#26 fix(FrontEnd): Ver Precio de evento a Inscribirse
  src/app/core/service/event.service.ts
  src/app/pages/event-detail/event-detail.component.ts
  src/app/pages/inscripcion-compra-evento/inscripcion-compra-evento.component.html
  src/app/pages/inscripcion-compra-evento/inscripcion-compra-evento.component.ts
Labels: fix

#29 Feature/ponente vista
  src/app/app.routes.ts
  src/app/core/service/auth.service.ts
  src/app/core/service/perfil.service.ts
  src/app/core/service/storage.service.ts
  src/app/pages/auth/login/login.component.ts
  src/app/pages/event-list/event-list.component.html
  src/app/pages/event-list/event-list.component.ts
  src/app/pages/participante/dashboard/dashboard.component.css
  src/app/pages/participante/inscription-details/inscription-details.component.spec.ts
  src/app/pages/participante/inscription-details/inscription-details.css
  src/app/pages/participante/inscription-details/inscription-details.html
  src/app/pages/participante/inscription-details/inscription-details.ts
  src/app/pages/participante/inscription/inscription.component.css
  src/app/pages/participante/inscription/inscription.component.html
  src/app/pages/participante/inscription/inscription.component.spec.ts
  src/app/pages/participante/inscription/inscription.component.ts
  src/app/pages/ponente/ponente-dashboard/ponente-dashboard.component.css
  src/app/pages/ponente/ponente-dashboard/ponente-dashboard.component.html
  src/app/pages/ponente/ponente-dashboard/ponente-dashboard.component.ts
  src/app/shared/components/navbar/navbar.component.html
  src/app/shared/components/navbar/navbar.component.ts
  src/app/shared/components/ponente-profile/ponente-profile.component.css
  src/app/shared/components/ponente-profile/ponente-profile.component.html
  src/app/shared/components/ponente-profile/ponente-profile.component.ts
  src/app/shared/components/update-profile-ponente/update-profile-ponente.component.html
  src/app/shared/components/update-profile-ponente/update-profile-ponente.component.ts
  src/app/shared/models/actualizarperfil-request-ponente.model.ts
  src/app/shared/models/auth-response.model.ts
  src/app/shared/models/register-responsePonente.model.ts
Labels: Fronted, fix

#30 Feature/inscripcion paypal email
  src/app/core/service/purchase.service.ts
  src/app/pages/event-list/event-list.component.ts
  src/app/pages/inscripcion-compra-evento/inscripcion-compra-evento.component.ts
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: Fronted

#33 Feature/buscar eventos
  src/app/pages/event-list/event-list.component.css
  src/app/pages/event-list/event-list.component.html
  src/app/pages/event-list/event-list.component.ts
Labels: Fronted

#36 Fixed/eventos crear actualizar admin
  src/app/app.routes.ts
  src/app/core/service/create-event.service.ts
  src/app/core/service/event.service.ts
  src/app/pages/admin/admin-dashboard/admin-dashboard.component.css
  src/app/pages/admin/admin-dashboard/admin-dashboard.component.html
  src/app/pages/admin/admin-dashboard/admin-dashboard.component.ts
  src/app/pages/admin/create-event/create-event.component.css
  src/app/pages/admin/create-event/create-event.component.html
  src/app/pages/admin/create-event/create-event.component.ts
  src/app/pages/admin/event-detail-admin/event-detail-admin.component.css
  src/app/pages/admin/event-detail-admin/event-detail-admin.component.html
  src/app/pages/admin/event-detail-admin/event-detail-admin.component.ts
  src/app/pages/admin/event-edit/event-edit.component.css
  src/app/pages/admin/event-edit/event-edit.component.html
  src/app/pages/admin/event-edit/event-edit.component.ts
  src/app/pages/admin/event-list-admin/event-list-admin.component.css
  src/app/pages/admin/event-list-admin/event-list-admin.component.html
  src/app/pages/admin/event-list-admin/event-list-admin.component.ts
  src/app/pages/auth/login/login.component.ts
  src/app/shared/components/navbar/navbar.component.ts
  src/app/shared/components/update-profile-ponente/update-profile-ponente.component.ts
Labels: Fronted, fix

#34 Feature/asistencia
  src/app/app.routes.ts
  src/app/core/service/asistencia.service.ts
  src/app/pages/asistencia/asistencia.component.css
  src/app/pages/asistencia/asistencia.component.html
  src/app/pages/asistencia/asistencia.component.ts
  src/app/pages/ponente/ponente-dashboard/ponente-dashboard.component.html
  src/app/pages/ponente/ponente-dashboard/ponente-dashboard.component.ts
  src/app/shared/models/ParticipanteActivoDTO.model.ts
Labels: Fronted

#37 feat(front): Pagina de landing page enrutado
  src/app/app.routes.ts
  src/app/js/script.js
  src/app/pages/home/home.component.css
  src/app/pages/home/home.component.html
  src/app/pages/home/home.component.ts
Labels: Fronted

#38 Feature/logear una vez
  src/app/core/service/auth.service.ts
  src/app/core/service/perfil.service.ts
  src/app/core/service/storage.service.ts
  src/app/pages/auth/login/login.component.html
  src/app/shared/components/ponente-profile/ponente-profile.component.ts
  src/app/shared/components/update-profile-ponente/update-profile-ponente.component.ts
  src/app/shared/components/update-profile/update-profile.component.ts
  src/app/shared/components/user-profile/user-profile.component.ts
  src/app/shared/models/actualizarperfil-request.model.ts
  src/app/shared/models/actualizarperfil-response.model.ts
  src/app/shared/models/auth-response.model.ts
  src/app/shared/models/register-response.model.ts
Labels: Fronted, fix

#40 eliminando un console log en login.component
  src/app/pages/auth/login/login.component.ts
Labels: Fronted
